---
name: spdk-nvda-nvmf

on:
  workflow_dispatch:

jobs:
  spdk-nvmf:
    runs-on: [self-hosted, nvda, mlx]
    env:
      gerrit_ref: ${{ inputs.gerrit_ref }}
      spdk_path: './spdk'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout SPDK repo from Gerrit
      uses: ./.github/actions/checkout_gerrit
      with:
        gerrit_ref: ${{ env.gerrit_ref }}
        spdk_path: ${{ env.spdk_path }}

    - name: Install dependencies
      run: |
        cd spdk
        sudo ./scripts/pkgdep.sh
        sudo ./test/common/config/autotest_setup.sh --install-deps --test-conf="fio,flamegraph,nvmecli,lcov"
